services:
  redis:
    container_name: "project-redis-${APP_ID}"
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - extnetwork
    restart: unless-stopped

  mysql:
    container_name: "project-mysql-${APP_ID}"
    image: "mysql:8.4"
    volumes:
      - ./docker/mysql/repassword.sh:/etc/mysql/repassword.sh
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_PREFIX: "${DB_PREFIX}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${DB_USERNAME}", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - extnetwork
    restart: unless-stopped

  appstore:
    container_name: "dootask-appstore-${APP_ID}"
    privileged: true
    image: "dootask/appstore:0.5.4"
    volumes:
      - shared_data:/usr/share/dootask
      - ${HOST_DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
      - ./:/var/www
    environment:
      HOST_PWD: "${PWD}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - extnetwork
    restart: unless-stopped

networks:
  extnetwork:
    name: "project-networks-${APP_ID}"

volumes:
  shared_data:
    name: "project-shared-data-${APP_ID}"
  redis_data:
    name: "project-redis-data-${APP_ID}"
