services:
  mysql:
    container_name: "project-local-mysql"
    image: "mysql:8.4"
    ports:
      - "23306:3306"
    volumes:
      - ./docker/mysql/repassword.sh:/etc/mysql/repassword.sh
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_PREFIX: "pre_"
      MYSQL_ROOT_PASSWORD: "local-root"
      MYSQL_DATABASE: "project"
      MYSQL_USER: "project"
      MYSQL_PASSWORD: "123456"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "project", "-p123456"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  redis:
    container_name: "project-local-redis"
    image: "redis:alpine"
    ports:
      - "26379:6379"
    volumes:
      - project-local-redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  appstore:
    container_name: "project-local-appstore"
    image: "dootask/appstore:0.5.4"
    privileged: true
    ports:
      - "19080:80"
    volumes:
      - project-local-shared:/usr/share/dootask
      - ${HOST_DOCKER_SOCK:-/var/run/docker.sock}:/var/run/docker.sock
      - ./:/var/www
    environment:
      HOST_PWD: "${PWD}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

volumes:
  project-local-shared:
  project-local-redis:
